name: Publish to NPM

on:
  push:
    branches:
      - main # when pushed to main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1' # set node version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Publish to NPM
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # npm secret token
        run: npm run publish-npm
